sudo: required

language: python

services:
  - docker

env:
  global:
  - secure: G41wNYuzuhVsFsZqpOjFR+LOr6w8xa6VJYJ+TSzZMhEpQuYQOc/u11hPwc3whyjYmVTpWZ+zr4Zt54xfnB06vYgO3kaudEnDzPBKxldgyWuSCIA36+uiQLc6h6SvmxFd9M0MmOWtbTVf3SZq1Pm0k47CSzxlYAdzFYUroaaRVp6oEgLRuMcfTrnmasCl8gLo8sTr5MKGP8Lo0bI6bI0i3ndnaB6+qU1bYbkDSptCKoPr6cxnl1EZlIhrPf3Bh846Kk6K1+LLTpQDg0dfkHUVRsY00PTNz9+GOmAbFpz4l08drCkvsJopwfO9VgVw6QuuEZ6DDLCKS5rr8HCF1RsW0w7e4xfwpP1buUa4dRjDZgIyEaKDXAD+sSVsgJN7Qj6c+FUj6UTY26w02eapNytEz499y0vLN8PRHk3WFpkFvAKRSjgVSip1LNjlnh6TeEqVdRGgkD8CrTCE6uIIkUHiy4onfn8JR+gNZyHHxIiu9pj4WbwnM70WbBFAz0zYbQtHbouAWih0oEzJCH8dX1AhSNNviwTBPlJNVvuy0vAAKxLOIrHvi7vYVm9w7m59oLN2GZxMordovdU0Fs/lsmcBJVE6sKzbg9Z/g9c0MJKikdPYkfh4aBZNYUSYOzMJs6EKJ55o19cxGvgNhUJbF8C9sjjWHor+50mMnhpOW9ORe1s=
  - secure: NrIVKp9yVBQAo0nXBowbRRiNgjpW8afDNFx3UXNm4+u7842qyoqahuaiJS5OpG9Ph+qgA4aBJajlmyYyms6fw/vlQ8Z3hou2EmemEVhD4tSps8yaAiZWdadFoAcD82MqHQ9/GwQCnZQCQvNEZx7wn50ysvbiD0nTbLRFZhgs+2gjy5+1LVupBuEgQN2aPTUx/dpqx2rMLjl7huTbKWnV3bOwzK7VFer0gtWk03VBTABRaAiXkSqdKegUmfVtaMZ0gQkl15aTArGOLh9u27Z0OQXNzOKicT8Q1jtrdF11Tef3avUrcxQHNMHa1bUAIAA4WcUWYqvLXMU1fAv6z7vq9rjt3Msq5mYil0fPjCdolcg/YA0rIC80K7Jh322evBmMUEM2YCmGynu5Lm25k9p260cS2BW4gVhpJJweRljS501gFdujqT4qcpW19nALrFMIhw4N0sS1ce3UXCaQWmXYPxDEbEXCMzxWhR8yLVDODUQvKoyNvnOD5Ixtk8j3/YbZPGUwyPpLJIwfrbhJNxVmia/m9S0gOYNHCkFSIIYA1J6ydbSAz2A+TuuDbLTqTBwWA+WZm/+OmDzhguTJBp/VBUdJvXBU91uy9Ro/d8fz3MORhURgtEDEz8h2WwvDXeXIkYgICAYxoaEL67g+uIbDhamsGrWFENfG3cyyXBrS+sM=
  - COMMIT=${TRAVIS_COMMIT::8}

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/gocd-agent-alpine-docker:v18.7.0  .
      - docker images
      - docker push $DOCKER_USERNAME/gocd-agent-alpine-docker:v18.7.0
    - stage: test
      script:
      - docker run --rm $DOCKER_USERNAME/gocd-agent-alpine-docker:v18.7.0 docker version
